## TUPLE IS IMMUTABLE--->>> IT MEANS IT CANNIT BE CHANGED WHEN ONCE CREATED
## IN TUPLE THE PARANTHESIS ARE OPTIONAL 
## fact hai bhai loggggg
marks = (95,98,97,95,97,96,97,94)

## TO CHECK THE OCCURENCE OF ANY ELEMENT 
print(marks.count(97))
## TO CHECK THE INDEX OF ANY ELEMENT
print(marks.index(94))